global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Components.Authorization;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Web;
global using JWFoundation.Services;
global using JWFoundation.Areas.Identity;
global using FoundationLib.Models;
global using FoundationLib.Data;
